apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.name }}-service
  namespace: {{ .Values.namespace }}
  labels:
    app: {{ .Values.name }}
spec:
  type: NodePort
  selector:
    app: {{ .Values.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.port }}
